# create configmap for cwagent config
apiVersion: v1
data:
  # Configuration is in Json format. No matter what configure change you make,
  # please keep the Json blob valid.
  cwagentconfig.json: |
      {
          "agent": {
              "region": "us-east-1"
          },
          "logs": {
              "metrics_collected": {
                  "kubernetes": {
                      "cluster_name": "eks",
                      "metrics_collection_interval": 60
                  }
              },
              "force_flush_interval": 5,
              "endpoint_override": "logs.us-east-1.amazonaws.com"
          },
          "metrics": {
              "metrics_collected": {
                  "statsd": {
                      "service_address": ":8125"
                  }
              }
          }
      }
kind: ConfigMap
metadata:
  name: cwagentconfig
  namespace: amazon-cloudwatch