name: 'Terraform'

on:
  workflow_dispatch:
    push:
    branches:
      - master
    pull_request:
    branches:
      - master

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve

#   k8s:
#     name: 'Kubernetes'
#     runs-on: ubuntu-latest
#     environment: production
#     steps:
#       - name: Configure kubernetes cluster
#         run: aws eks --region us-east-1 update-kubeconfig --name eks
#       - name:
#         run: kubectl apply -f webapp.yaml

